In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/supply_chain_data.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [2]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1000
Columns: 18

In [3]:
df.head()

,OrderID,OrderDate,ProductID,Product,Category,SupplierID,Supplier,SupplierCity,Warehouse,CustomerCity,Quantity,UnitCost,UnitPrice,ShippingCost,LeadTimeDays,OrderStatus,StockLevel,ReorderPoint
0,ORD00001,2025-01-13,P011,Storage Box,Home & Office,S001,Alpha Supply Co,Pune,Hyderabad,Bengaluru,4,6.5,16.99,19.40,7,Delivered,228,36
1,ORD00002,2025-02-17,P001,Wireless Mouse,Electronics,S001,Alpha Supply Co,Pune,Hyderabad,Bengaluru,1,8.5,18.99,10.50,11,Processing,143,50
2,ORD00003,2025-10-29,P004,Desk Lamp,Home & Office,S004,Delta Wholesale,Bengaluru,Mumbai,Nagpur,2,12.5,27.99,21.24,12,Returned,87,60
3,ORD00004,2025-02-17,P006,Notebook Pack,Stationery,S001,Alpha Supply Co,Pune,Pune,Hyderabad,2,2.8,7.49,23.47,7,Delivered,154,58
4,ORD00005,2025-07-13,P009,Backpack,Lifestyle,S001,Alpha Supply Co,Pune,Pune,Pune,1,18.0,39.99,13.44,8,Delivered,147,49

In [4]:
df.columns.tolist()

['OrderID',
 'OrderDate',
 'ProductID',
 'Product',
 'Category',
 'SupplierID',
 'Supplier',
 'SupplierCity',
 'Warehouse',
 'CustomerCity',
 'Quantity',
 'UnitCost',
 'UnitPrice',
 'ShippingCost',
 'LeadTimeDays',
 'OrderStatus',
 'StockLevel',
 'ReorderPoint']

In [5]:
print("Missing values:", df.isnull().sum().sum())

Missing values: 0

In [6]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate Order IDs:", df["OrderID"].duplicated().sum())

Duplicate rows: 0
Duplicate Order IDs: 0

In [7]:
df["ShippingCost"].describe()

count    1000.000000
mean       18.299630
std         7.524566
min         5.010000
25%        12.722500
50%        18.135000
75%        23.110000
max        56.690000
Name: ShippingCost, dtype: float64

In [8]:
df["OrderStatus"].value_counts()

OrderStatus
Delivered     422
Shipped       155
Processing    145
Cancelled     145
Returned      133
Name: count, dtype: int64

In [9]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"])

In [10]:
df.dtypes

OrderID                    str
OrderDate       datetime64[us]
ProductID                  str
Product                    str
Category                   str
SupplierID                 str
Supplier                   str
SupplierCity               str
Warehouse                  str
CustomerCity               str
Quantity                 int64
UnitCost               float64
UnitPrice              float64
ShippingCost           float64
LeadTimeDays             int64
OrderStatus                str
StockLevel               int64
ReorderPoint             int64
dtype: object

In [11]:
df["Sales"] = df["Quantity"] * df["UnitPrice"]

In [12]:
df["Cost"] = df["Quantity"] * df["UnitCost"]

In [13]:
df["Profit"] = df["Sales"] - df["Cost"] - df["ShippingCost"]

In [14]:
df[["Product", "Quantity", "UnitPrice", "UnitCost",
    "ShippingCost", "Sales", "Cost", "Profit"]].head()

,Product,Quantity,UnitPrice,UnitCost,ShippingCost,Sales,Cost,Profit
0,Storage Box,4,16.99,6.5,19.40,67.96,26.0,22.56
1,Wireless Mouse,1,18.99,8.5,10.50,18.99,8.5,-0.01
2,Desk Lamp,2,27.99,12.5,21.24,55.98,25.0,9.74
3,Notebook Pack,2,7.49,2.8,23.47,14.98,5.6,-14.09
4,Backpack,1,39.99,18.0,13.44,39.99,18.0,8.55

In [15]:
print("Total Sales:", round(df["Sales"].sum(), 2))

Total Sales: 100704.45

In [16]:
print("Total Product Cost:", round(df["Cost"].sum(), 2))

Total Product Cost: 45853.5

In [17]:
print("Total Shipping Cost:", round(df["ShippingCost"].sum(), 2))

Total Shipping Cost: 18299.63

In [18]:
print("Total Profit:", round(df["Profit"].sum(), 2))

Total Profit: 36551.32

In [19]:
print("Total Sales:", round(df["Sales"].sum(), 2))

Total Sales: 100704.45

In [20]:
print("Total Product Cost:", round(df["Cost"].sum(), 2))

Total Product Cost: 45853.5

In [21]:
print("Total Shipping Cost:", round(df["ShippingCost"].sum(), 2))

Total Shipping Cost: 18299.63

In [22]:
print("Profitable Orders:", (df["Profit"] > 0).sum())
print("Loss-Making Orders:", (df["Profit"] < 0).sum())

Profitable Orders: 685
Loss-Making Orders: 315

In [23]:
total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()

print("Profit Margin:", round((total_profit / total_sales) * 100, 2), "%")

Profit Margin: 36.3 %

In [24]:
product_sales = df.groupby("Product")["Sales"].sum().sort_values(ascending=False)

product_sales

Product
Office Chair         36657.18
Bluetooth Speaker    13901.91
Backpack             11797.05
Desk Lamp             7137.45
Desk Organizer        6016.99
Storage Box           5521.75
Wireless Mouse        5431.14
Water Bottle          5336.44
Phone Stand           3247.50
USB-C Cable           2107.89
Notebook Pack         1887.48
Ballpoint Pens        1661.67
Name: Sales, dtype: float64

In [25]:
product_profit = df.groupby("Product")["Profit"].sum().sort_values(ascending=False)

product_profit

Product
Office Chair         16075.54
Bluetooth Speaker     5292.35
Backpack              4941.45
Desk Lamp             2615.38
Desk Organizer        2288.76
Storage Box           1873.83
Water Bottle          1780.70
Wireless Mouse        1510.11
Phone Stand            929.57
USB-C Cable             60.20
Notebook Pack         -317.78
Ballpoint Pens        -498.79
Name: Profit, dtype: float64

In [26]:
product_quantity = df.groupby("Product")["Quantity"].sum().sort_values(ascending=False)

product_quantity

Product
Water Bottle         356
Ballpoint Pens       333
Storage Box          325
Bluetooth Speaker    309
Desk Organizer       301
Backpack             295
Wireless Mouse       286
Office Chair         282
Desk Lamp            255
Notebook Pack        252
Phone Stand          250
USB-C Cable          211
Name: Quantity, dtype: int64

In [27]:
product_summary = df.groupby("Product").agg(
    Total_Sales=("Sales", "sum"),
    Total_Cost=("Cost", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum")
).sort_values("Total_Sales", ascending=False)

product_summary.round(2)

                   Total_Sales  Total_Cost  Total_Profit  Total_Quantity
Product
Office Chair          36657.18     19176.0      16075.54             282
Bluetooth Speaker     13901.91      6798.0       5292.35             309
Backpack              11797.05      5310.0       4941.45             295
Desk Lamp              7137.45      3187.5       2615.38             255
Desk Organizer         6016.99      2107.0       2288.76             301
Storage Box            5521.75      2112.5       1873.83             325
Wireless Mouse         5431.14      2431.0       1510.11             286
Water Bottle           5336.44      1851.2       1780.70             356
Phone Stand            3247.50      1000.0        929.57             250
USB-C Cable            2107.89       675.2         60.20             211
Notebook Pack          1887.48       705.6       -317.78             252
Ballpoint Pens         1661.67       499.5       -498.79             333

In [29]:
product_summary.head(5).round(2)

                   Total_Sales  Total_Cost  Total_Profit  Total_Quantity
Product
Office Chair          36657.18     19176.0      16075.54             282
Bluetooth Speaker     13901.91      6798.0       5292.35             309
Backpack              11797.05      5310.0       4941.45             295
Desk Lamp              7137.45      3187.5       2615.38             255
Desk Organizer         6016.99      2107.0       2288.76             301

In [30]:
supplier_sales = df.groupby("Supplier")["Sales"].sum().sort_values(ascending=False)

supplier_sales

Supplier
Delta Wholesale           20170.83
Evergreen Distributors    17931.88
BrightSource Ltd          17892.54
FirstLine Goods           16048.95
Alpha Supply Co           14562.54
CoreTrade Partners        14097.71
Name: Sales, dtype: float64

In [31]:
supplier_profit = df.groupby("Supplier")["Profit"].sum().sort_values(ascending=False)

supplier_profit

Supplier
Delta Wholesale           7729.84
Evergreen Distributors    6756.76
BrightSource Ltd          6256.11
FirstLine Goods           5711.85
CoreTrade Partners        5093.53
Alpha Supply Co           5003.23
Name: Profit, dtype: float64

In [32]:
supplier_orders = df.groupby("Supplier")["OrderID"].count().sort_values(ascending=False)

supplier_orders

Supplier
FirstLine Goods           184
BrightSource Ltd          181
Alpha Supply Co           171
Delta Wholesale           163
Evergreen Distributors    159
CoreTrade Partners        142
Name: OrderID, dtype: int64

In [33]:
supplier_summary = df.groupby("Supplier").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Orders=("OrderID", "count"),
    Avg_Lead_Time=("LeadTimeDays", "mean")
).sort_values("Total_Sales", ascending=False)

supplier_summary.round(2)

                        Total_Sales  Total_Profit  Total_Orders  Avg_Lead_Time
Supplier
Delta Wholesale            20170.83       7729.84           163           6.50
Evergreen Distributors     17931.88       6756.76           159           6.47
BrightSource Ltd           17892.54       6256.11           181           6.66
FirstLine Goods            16048.95       5711.85           184           6.29
Alpha Supply Co            14562.54       5003.23           171           6.43
CoreTrade Partners         14097.71       5093.53           142           6.46

In [34]:
supplier_summary.head(3).round(2)

                        Total_Sales  Total_Profit  Total_Orders  Avg_Lead_Time
Supplier
Delta Wholesale            20170.83       7729.84           163           6.50
Evergreen Distributors     17931.88       6756.76           159           6.47
BrightSource Ltd           17892.54       6256.11           181           6.66

In [35]:
warehouse_sales = df.groupby("Warehouse")["Sales"].sum().sort_values(ascending=False)
warehouse_sales

Warehouse
Bengaluru    23268.01
Hyderabad    20682.35
Delhi        20272.49
Mumbai       19985.08
Pune         16496.52
Name: Sales, dtype: float64

In [36]:
warehouse_profit = df.groupby("Warehouse")["Profit"].sum().sort_values(ascending=False)
warehouse_profit

Warehouse
Bengaluru    8458.49
Delhi        7470.73
Hyderabad    7391.71
Mumbai       7257.52
Pune         5972.87
Name: Profit, dtype: float64

In [37]:
warehouse_orders = df.groupby("Warehouse")["OrderID"].count().sort_values(ascending=False)
warehouse_orders

Warehouse
Bengaluru    216
Hyderabad    204
Mumbai       200
Delhi        194
Pune         186
Name: OrderID, dtype: int64

In [38]:
warehouse_summary = df.groupby("Warehouse").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Orders=("OrderID", "count"),
    Avg_Lead_Time=("LeadTimeDays", "mean"),
    Avg_Stock_Level=("StockLevel", "mean")
).sort_values("Total_Sales", ascending=False)

warehouse_summary.round(2)

,Total_Sales,Total_Profit,Total_Orders,Avg_Lead_Time,Avg_Stock_Level
Warehouse,,,,,
Bengaluru,23268.01,8458.49,216,6.80,121.68
Hyderabad,20682.35,7391.71,204,6.40,122.05
Delhi,20272.49,7470.73,194,6.02,125.49
Mumbai,19985.08,7257.52,200,6.84,124.19
Pune,16496.52,5972.87,186,6.24,133.66

In [39]:
warehouse_summary.head(1).round(2)

,Total_Sales,Total_Profit,Total_Orders,Avg_Lead_Time,Avg_Stock_Level
Warehouse,,,,,
Bengaluru,23268.01,8458.49,216,6.8,121.68

In [40]:
df[["Product", "Warehouse", "StockLevel", "ReorderPoint"]].head(10)

             Product  Warehouse  StockLevel  ReorderPoint
0        Storage Box  Hyderabad         228            36
1     Wireless Mouse  Hyderabad         143            50
2          Desk Lamp     Mumbai          87            60
3      Notebook Pack       Pune         154            58
4           Backpack       Pune         147            49
5        Storage Box      Delhi          25            73
6        Storage Box  Hyderabad          18            46
7  Bluetooth Speaker       Pune          56            66
8     Wireless Mouse  Bengaluru          54            88
9  Bluetooth Speaker  Hyderabad         191            79

In [41]:
below_reorder = df[df["StockLevel"] < df["ReorderPoint"]]
below_reorder.shape

(217, 21)

In [42]:
at_or_below_reorder = df[df["StockLevel"] <= df["ReorderPoint"]]
at_or_below_reorder.shape

(223, 21)

In [43]:
df["ReorderStatus"] = df.apply(
    lambda row: "Reorder Needed"
    if row["StockLevel"] <= row["ReorderPoint"]
    else "Stock OK",
    axis=1
)

df["ReorderStatus"].value_counts()

ReorderStatus
Stock OK          777
Reorder Needed    223
Name: count, dtype: int64

In [44]:
inventory_summary = df.groupby("Product").agg(
    Avg_Stock_Level=("StockLevel", "mean"),
    Avg_Reorder_Point=("ReorderPoint", "mean"),
    Reorder_Needed_Count=("ReorderStatus", lambda x: (x == "Reorder Needed").sum())
).sort_values("Reorder_Needed_Count", ascending=False)

inventory_summary.round(2)

                   Avg_Stock_Level  Avg_Reorder_Point  Reorder_Needed_Count
Product
Bluetooth Speaker           117.45              57.70                    26
Storage Box                 123.17              56.20                    23
Desk Organizer              121.50              55.67                    22
Water Bottle                126.00              56.76                    21
Notebook Pack               109.33              56.47                    21
Backpack                    123.87              55.94                    19
Office Chair                125.38              55.82                    18
Phone Stand                 125.94              55.15                    17
Desk Lamp                   120.81              57.07                    16
Ballpoint Pens              140.78              59.79                    16
USB-C Cable                 135.82              59.29                    12
Wireless Mouse              133.47              58.88                    12

In [45]:
df["OrderStatus"].value_counts()

OrderStatus
Delivered     422
Shipped       155
Processing    145
Cancelled     145
Returned      133
Name: count, dtype: int64

In [46]:
status_sales = df.groupby("OrderStatus")["Sales"].sum().sort_values(ascending=False)
status_sales.round(2)

OrderStatus
Delivered     42914.79
Returned      16126.49
Shipped       14773.84
Cancelled     14076.72
Processing    12812.61
Name: Sales, dtype: float64

In [47]:
status_profit = df.groupby("OrderStatus")["Profit"].sum().sort_values(ascending=False)
status_profit.round(2)

OrderStatus
Delivered     15469.08
Returned       6231.35
Shipped        5331.51
Cancelled      5092.06
Processing     4427.32
Name: Profit, dtype: float64

In [48]:
status_lead_time = df.groupby("OrderStatus")["LeadTimeDays"].mean()
status_lead_time.round(2)

OrderStatus
Cancelled     6.32
Delivered     6.28
Processing    6.83
Returned      6.51
Shipped       6.75
Name: LeadTimeDays, dtype: float64

In [49]:
status_summary = df.groupby("OrderStatus").agg(
    Total_Orders=("OrderID", "count"),
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Avg_Lead_Time=("LeadTimeDays", "mean")
)

status_summary.round(2)

             Total_Orders  Total_Sales  Total_Profit  Avg_Lead_Time
OrderStatus
Cancelled             145     14076.72       5092.06           6.32
Delivered             422     42914.79      15469.08           6.28
Processing            145     12812.61       4427.32           6.83
Returned              133     16126.49       6231.35           6.51
Shipped               155     14773.84       5331.51           6.75

In [50]:
df["Month"] = df["OrderDate"].dt.to_period("M")

In [51]:
monthly_sales = df.groupby("Month")["Sales"].sum()
monthly_sales.round(2)

Month
2025-01    10295.61
2025-02     8018.89
2025-03    10081.82
2025-04     7276.22
2025-05     7091.63
2025-06     9541.37
2025-07     9780.41
2025-08     9057.41
2025-09     6471.51
2025-10     7875.94
2025-11     8425.36
2025-12     6788.28
Freq: M, Name: Sales, dtype: float64

In [52]:
monthly_profit = df.groupby("Month")["Profit"].sum()
monthly_profit.round(2)

Month
2025-01    3961.68
2025-02    2821.72
2025-03    3644.39
2025-04    2421.39
2025-05    2458.77
2025-06    3639.94
2025-07    3712.37
2025-08    3403.30
2025-09    2212.36
2025-10    2742.17
2025-11    3166.65
2025-12    2366.58
Freq: M, Name: Profit, dtype: float64

In [53]:
monthly_summary = df.groupby("Month").agg(
    Total_Orders=("OrderID", "count"),
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Avg_Lead_Time=("LeadTimeDays", "mean")
)

monthly_summary.round(2)

         Total_Orders  Total_Sales  Total_Profit  Avg_Lead_Time
Month
2025-01            89     10295.61       3961.68           6.47
2025-02            86      8018.89       2821.72           6.37
2025-03            88     10081.82       3644.39           6.03
2025-04            78      7276.22       2421.39           6.08
2025-05            77      7091.63       2458.77           6.47
2025-06            84      9541.37       3639.94           6.40
2025-07            91      9780.41       3712.37           6.49
2025-08            77      9057.41       3403.30           6.96
2025-09            79      6471.51       2212.36           6.84
2025-10            93      7875.94       2742.17           6.87
2025-11            80      8425.36       3166.65           6.39
2025-12            78      6788.28       2366.58           6.23

In [54]:
monthly_sales.idxmax(), monthly_sales.max()

(Period('2025-01', 'M'), np.float64(10295.61))

In [55]:
total_orders = df["OrderID"].nunique()
total_sales = df["Sales"].sum()
total_cost = df["Cost"].sum()
total_profit = df["Profit"].sum()
avg_lead_time = df["LeadTimeDays"].mean()

print("Total Orders:", total_orders)
print("Total Sales:", round(total_sales, 2))
print("Total Cost:", round(total_cost, 2))
print("Total Profit:", round(total_profit, 2))
print("Average Lead Time:", round(avg_lead_time, 2), "days")

Total Orders: 1000
Total Sales: 100704.45
Total Cost: 45853.5
Total Profit: 36551.32
Average Lead Time: 6.47 days

In [56]:
profit_margin = (total_profit / total_sales) * 100
print("Profit Margin:", round(profit_margin, 2), "%")

Profit Margin: 36.3 %

In [57]:
df.head()

,OrderID,OrderDate,ProductID,Product,Category,SupplierID,Supplier,SupplierCity,Warehouse,CustomerCity,...,ShippingCost,LeadTimeDays,OrderStatus,StockLevel,ReorderPoint,Sales,Cost,Profit,ReorderStatus,Month
0,ORD00001,2025-01-13,P011,Storage Box,Home & Office,S001,Alpha Supply Co,Pune,Hyderabad,Bengaluru,...,19.40,7,Delivered,228,36,67.96,26.0,22.56,Stock OK,2025-01
1,ORD00002,2025-02-17,P001,Wireless Mouse,Electronics,S001,Alpha Supply Co,Pune,Hyderabad,Bengaluru,...,10.50,11,Processing,143,50,18.99,8.5,-0.01,Stock OK,2025-02
2,ORD00003,2025-10-29,P004,Desk Lamp,Home & Office,S004,Delta Wholesale,Bengaluru,Mumbai,Nagpur,...,21.24,12,Returned,87,60,55.98,25.0,9.74,Stock OK,2025-10
3,ORD00004,2025-02-17,P006,Notebook Pack,Stationery,S001,Alpha Supply Co,Pune,Pune,Hyderabad,...,23.47,7,Delivered,154,58,14.98,5.6,-14.09,Stock OK,2025-02
4,ORD00005,2025-07-13,P009,Backpack,Lifestyle,S001,Alpha Supply Co,Pune,Pune,Pune,...,13.44,8,Delivered,147,49,39.99,18.0,8.55,Stock OK,2025-07

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        1000 non-null   str
 1   OrderDate      1000 non-null   datetime64[us]
 2   ProductID      1000 non-null   str
 3   Product        1000 non-null   str
 4   Category       1000 non-null   str
 5   SupplierID     1000 non-null   str
 6   Supplier       1000 non-null   str
 7   SupplierCity   1000 non-null   str
 8   Warehouse      1000 non-null   str
 9   CustomerCity   1000 non-null   str
 10  Quantity       1000 non-null   int64
 11  UnitCost       1000 non-null   float64
 12  UnitPrice      1000 non-null   float64
 13  ShippingCost   1000 non-null   float64
 14  LeadTimeDays   1000 non-null   int64
 15  OrderStatus    1000 non-null   str
 16  StockLevel     1000 non-null   int64
 17  ReorderPoint   1000 non-null   int64
 18  Sales          1000 non-null   float64
 19  Cost           1000 non-null   float64
 20  Profit         1000 non-null   float64
 21  ReorderStatus  1000 non-null   str
 22  Month          1000 non-null   period[M]
dtypes: datetime64[us](1), float64(6), int64(4), period[M](1), str(11)
memory usage: 179.8 KB

In [59]:
df.to_csv("../data/processed/supply_chain_cleaned.csv", index=False)

In [60]:
import os

os.path.exists("../data/processed/supply_chain_cleaned.csv")

True

In [61]:
cleaned_df = pd.read_csv("../data/processed/supply_chain_cleaned.csv")

print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])
cleaned_df.head()

Rows: 1000
Columns: 23

,OrderID,OrderDate,ProductID,Product,Category,SupplierID,Supplier,SupplierCity,Warehouse,CustomerCity,...,ShippingCost,LeadTimeDays,OrderStatus,StockLevel,ReorderPoint,Sales,Cost,Profit,ReorderStatus,Month
0,ORD00001,2025-01-13,P011,Storage Box,Home & Office,S001,Alpha Supply Co,Pune,Hyderabad,Bengaluru,...,19.40,7,Delivered,228,36,67.96,26.0,22.56,Stock OK,2025-01
1,ORD00002,2025-02-17,P001,Wireless Mouse,Electronics,S001,Alpha Supply Co,Pune,Hyderabad,Bengaluru,...,10.50,11,Processing,143,50,18.99,8.5,-0.01,Stock OK,2025-02
2,ORD00003,2025-10-29,P004,Desk Lamp,Home & Office,S004,Delta Wholesale,Bengaluru,Mumbai,Nagpur,...,21.24,12,Returned,87,60,55.98,25.0,9.74,Stock OK,2025-10
3,ORD00004,2025-02-17,P006,Notebook Pack,Stationery,S001,Alpha Supply Co,Pune,Pune,Hyderabad,...,23.47,7,Delivered,154,58,14.98,5.6,-14.09,Stock OK,2025-02
4,ORD00005,2025-07-13,P009,Backpack,Lifestyle,S001,Alpha Supply Co,Pune,Pune,Pune,...,13.44,8,Delivered,147,49,39.99,18.0,8.55,Stock OK,2025-07

In [62]:
import sqlite3

print("SQLite is ready!")

SQLite is ready!

In [63]:
conn = sqlite3.connect("../database/supply_chain.db")

print("Database connected successfully!")

Database connected successfully!

In [64]:
import pandas as pd

cleaned_df = pd.read_csv("../data/processed/supply_chain_cleaned.csv")

cleaned_df.head()

,OrderID,OrderDate,ProductID,Product,Category,SupplierID,Supplier,SupplierCity,Warehouse,CustomerCity,...,ShippingCost,LeadTimeDays,OrderStatus,StockLevel,ReorderPoint,Sales,Cost,Profit,ReorderStatus,Month
0,ORD00001,2025-01-13,P011,Storage Box,Home & Office,S001,Alpha Supply Co,Pune,Hyderabad,Bengaluru,...,19.40,7,Delivered,228,36,67.96,26.0,22.56,Stock OK,2025-01
1,ORD00002,2025-02-17,P001,Wireless Mouse,Electronics,S001,Alpha Supply Co,Pune,Hyderabad,Bengaluru,...,10.50,11,Processing,143,50,18.99,8.5,-0.01,Stock OK,2025-02
2,ORD00003,2025-10-29,P004,Desk Lamp,Home & Office,S004,Delta Wholesale,Bengaluru,Mumbai,Nagpur,...,21.24,12,Returned,87,60,55.98,25.0,9.74,Stock OK,2025-10
3,ORD00004,2025-02-17,P006,Notebook Pack,Stationery,S001,Alpha Supply Co,Pune,Pune,Hyderabad,...,23.47,7,Delivered,154,58,14.98,5.6,-14.09,Stock OK,2025-02
4,ORD00005,2025-07-13,P009,Backpack,Lifestyle,S001,Alpha Supply Co,Pune,Pune,Pune,...,13.44,8,Delivered,147,49,39.99,18.0,8.55,Stock OK,2025-07

In [65]:
cleaned_df.to_sql(
    "supply_chain",
    conn,
    if_exists="replace",
    index=False
)

print("Data loaded into SQLite successfully!")

Data loaded into SQLite successfully!

In [66]:
pd.read_sql_query(
    "SELECT COUNT(*) AS total_rows FROM supply_chain",
    conn
)

   total_rows
0        1000

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../database/supply_chain.db")

print("Connected to database successfully!")

Connected to database successfully!

In [2]:
pd.read_sql_query("""
SELECT COUNT(DISTINCT OrderID) AS Total_Orders
FROM supply_chain;
""", conn)

   Total_Orders
0          1000

In [3]:
pd.read_sql_query("""
SELECT ROUND(SUM(Sales), 2) AS Total_Sales
FROM supply_chain;
""", conn)

   Total_Sales
0    100704.45

In [4]:
pd.read_sql_query("""
SELECT ROUND(SUM(Profit), 2) AS Total_Profit
FROM supply_chain;
""", conn)

   Total_Profit
0      36551.32

In [5]:
pd.read_sql_query("""
SELECT
    Product,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM supply_chain
GROUP BY Product
ORDER BY Total_Sales DESC
LIMIT 5;
""", conn)

             Product  Total_Sales  Total_Profit
0       Office Chair     36657.18      16075.54
1  Bluetooth Speaker     13901.91       5292.35
2           Backpack     11797.05       4941.45
3          Desk Lamp      7137.45       2615.38
4     Desk Organizer      6016.99       2288.76

In [6]:
pd.read_sql_query("""
SELECT
    Supplier,
    COUNT(*) AS Total_Orders,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(AVG(LeadTimeDays), 2) AS Avg_Lead_Time
FROM supply_chain
GROUP BY Supplier
ORDER BY Total_Sales DESC;
""", conn)

,Supplier,Total_Orders,Total_Sales,Total_Profit,Avg_Lead_Time
0,Delta Wholesale,163,20170.83,7729.84,6.50
1,Evergreen Distributors,159,17931.88,6756.76,6.47
2,BrightSource Ltd,181,17892.54,6256.11,6.66
3,FirstLine Goods,184,16048.95,5711.85,6.29
4,Alpha Supply Co,171,14562.54,5003.23,6.43
5,CoreTrade Partners,142,14097.71,5093.53,6.46